# Generated by Django 3.2.2 on 2021-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dep_time', models.CharField(max_length=10)),
                ('Journey_date', models.CharField(max_length=20)),
                ('Arrival_time', models.CharField(max_length=10)),
                ('Total_stops', models.IntegerField()),
                ('duration_hr', models.IntegerField()),
                ('dest', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('flight', models.CharField(max_length=20)),
            ],
        ),
    ]
